from Tankwar.modules.GameLevel import GameLevel
from Tankwar.modules.interfaces.gameEndIterface import gameEndIterface
from Tankwar.modules.interfaces.gameStartInterface import gameStartInterface
from Tankwar.modules.interfaces.switchLevelIterface import switchLevelIterface