from modules.GameLevel import GameLevel
from modules.interfaces.gameEndInterface import gameEndInterface
from modules.interfaces.gameStartInterface import gameStartInterface
from modules.interfaces.switchLevelInterface import switchLevelInterface